apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: frontend
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql-container
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: rootpassword
            - name: MYSQL_DATABASE
              value: mydatabase
            - name: MYSQL_USER
              value: user
            - name: MYSQL_PASSWORD
              value: userpassword
          ports:
            - containerPort: 3306
      restartPolicy: Always
