apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: frontend
  labels:
    app: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp-container
          image: webapp:latest
          ports:
            - containerPort: 80
          env:
            - name: DATABASE_HOST
              value: 10.244.0.3
            - name: DATABASE_PORT
              value: "3306"
            - name: DATABASE_NAME
              value: mydatabase
            - name: DATABASE_USER
              value: user
            - name: DATABASE_PASSWORD
              value: userpassword
      restartPolicy: Always